Create a postLogin handler
Dipress/bgwebmon-go pull request #4
Opened 2018-07-12 17:56 UTC by Dipress

2018-07-12 18:15 UTC, romanyx requested changes
Нужны поправки по коду

2018-07-12 18:15 UTC, romanyx commented on internal/server/responses.go
> +	http.Error(w, internalServerErrorMessage, http.StatusInternalServerError)
Нужно и возвращать также как и ошибку в формате json а не просто текст.

2018-07-12 18:15 UTC, romanyx commented on internal/server/responses.go
> +	w.Header().Set("Content-type", "application/json")
Нужно вынести в middleware

2018-07-12 18:15 UTC, romanyx commented on internal/server/responses.go
> +	w.Header().Set("Content-type", "application/json")
Нужно вынести в middleware

2018-07-12 18:15 UTC, romanyx commented on internal/server/user/user.go
> +		return ErrorResponse{Status: "error", Message: "login or password a wrong"}
"login or password is invalid" и нужно перенести в константу

2018-07-12 18:15 UTC, romanyx commented on internal/server/user/user.go
> +	mySigningKey := []byte("secret")
эту переменнуж желательно указывать флагом при старте, и передавать в хендлер также как и соединение с базой данных

2018-07-12 18:15 UTC, romanyx commented on internal/server/user/user.go
> +		"exp":    time.Now().Add(time.Hour * 24).Unix(),
время жизни должно быть константой

2018-07-12 18:15 UTC, romanyx commented on main.go
> +	db, err := openDB("username:password@tcp(127.0.0.1:3306)/bgbilling_development")
Стринг DSN тоже желательно флагом сделать

2018-07-12 18:15 UTC, romanyx commented on internal/server/user/user.go
> +	case nil:
Не понял что это за `case` такой с nil.

2018-07-13 09:30 UTC, romanyx requested changes

2018-07-13 09:30 UTC, romanyx commented on internal/server/responses.go
> +	w.Header().Set("Content-type", "application/json")
Вынести в middleware

2018-07-13 09:30 UTC, romanyx commented on internal/server/user/user.go
> +	errorLoginOrPassword = "login or password are invalid"
invalidLoginOrPasswordMessage

2018-07-13 09:30 UTC, romanyx commented on internal/server/user/user.go
> +var expiredTime = time.Now().Add(time.Hour * 24).Unix()
Нужно вынести в константу `time.Hour * 24` все остальное вернуть на свое место

2018-07-13 09:30 UTC, romanyx commented on internal/server/user/user.go
> +func (model Model) Validate() error {
Мне кажется не нужно валидацию выносить в метод модели, валидацию вообще стоит вынести в отдельный интерфейс, с методом Validate(user Model) error и ошибкой будет возвращаться структура ValidationErrorResponse. Пакет позволяет делать валидацию конкретных данных, а не только полей структуры.

2018-07-18 08:30 UTC, romanyx commented on internal/server/auth/auth.go
> +	Create(userID int) (string, error)
По [конвенци](https://golang.org/doc/effective_go.html#interface-names), метод у интерфейса `tokener` должен быть `Token`

2018-07-18 08:30 UTC, romanyx commented on internal/server/auth/auth.go
> +	token, err := u.Create(user.ID)
`u.tokener.Token(user.ID)`

2018-07-18 08:30 UTC, romanyx commented on internal/server/auth/auth_test.go
> +func Test_jwtTokenCreate(t *testing.T) {
Название теста нужно поменять, [правильно](https://golang.org/pkg/testing/) называть так Test_jwtToken_Create, в других тестах тоже измени

2018-08-06 08:53 UTC, romanyx requested changes
Нужен unit тест для `Authenticate`

2018-08-06 08:53 UTC, romanyx commented on internal/server/post_login.go
> +				internalServerResponse(w, internalServerErrorMessage)
`internalServerErrorResponse`

2018-08-06 18:05 UTC, Dipress commented on internal/server/post_login.go
> +				internalServerResponse(w, internalServerErrorMessage)
Хорршо. Подскажи как надо проверить Authenticate. Какие шаги надо сделать. Мне не понятно просто как это должно быть сделано.

2018-08-06 20:26 UTC, romanyx requested changes

2018-08-06 20:26 UTC, romanyx commented on internal/server/auth/auth.go
> +type findByLogin struct{}
в этой структуре должен содержаться экземпляр на базу данных, так как она непосредственно использует его.

2018-08-06 20:26 UTC, romanyx commented on internal/server/auth/auth.go
> +	Find(db *sql.DB, login string, model *Model) error
эксземпляр на базу данных не должен передаваться сюда

2018-08-06 20:26 UTC, romanyx commented on internal/server/auth/auth.go
> +		db:        db,
база данных тут не нужна она используется только в `finder`

2018-08-06 20:26 UTC, romanyx commented on internal/server/post_login.go
> +				internalServerResponse(w, internalServerErrorMessage)
Также как и все другое, у тебя есть структур у которой есть метод `Authenticate` тебе нужно покрыть ее тестами, для этого тебе нужно для каждого шага вставлять мок нужного интерфейса. Для примера смотри Test_postLogin как сделано в нем.

2018-08-07 12:01 UTC, Dipress commented on internal/server/auth/auth.go
> +type findByLogin struct{}
Тогда это структура должно быть экпрортирована и иметь фабрику (NewFinder) ?

2018-08-07 12:33 UTC, Dipress commented on internal/server/auth/auth.go
> +type findByLogin struct{}
Хотя может просто передать db вот так :
type findByLogin struct {
	db *sql.DB
}
func NewAuthenticator(db *sql.DB, secretKey string) Authenticator {
	return &authenticator{
		secretKey: secretKey,
		validator: ozzoValidator{},
		tokener:   jwtToken{},
		checker:   passwordChecker{},
		decoder:   bodyDecoder{},
		finder:    findByLogin{db: db},
	}

?

2018-09-01 21:00 UTC, romanyx requested changes

2018-09-01 21:00 UTC, romanyx commented on internal/server/post_login.go
> +				internalServerErrorResponse(w, internalServerErrorMessage)
`internalServerErrorMessage` сюда не нужно передавать. Нужно перенести эту конастанту в `responses.go`, пусть лежит там и вызывается тоже там.

2018-09-01 21:00 UTC, romanyx commented on internal/server/responses.go
> +func internalServerErrorResponse(w http.ResponseWriter, resp interface{}) {
Аргумент `resp` тут не нужен

2018-09-01 21:00 UTC, romanyx commented on internal/server/responses.go
> +	json.NewEncoder(w).Encode(resp)
Передавай сюда константу `internalServerErrorMessage` текст всегда один будет

2018-09-01 21:00 UTC, romanyx commented on internal/server/responses.go
> +	json.NewEncoder(w).Encode(resp)
Давай не игнорить ошибки при энкодинге, если тут будет ошибка, вызывай `internalServerErrorResponse(w)`

2018-09-01 21:00 UTC, romanyx commented on internal/server/responses.go
> +	json.NewEncoder(w).Encode(resp)
Encode тоже лишнее, делай `fmt.Fprint`

2018-09-01 21:00 UTC, romanyx commented on internal/server/responses.go
> +	json.NewEncoder(w).Encode(resp)
тоже проверь ошибку

2018-09-01 21:02 UTC, romanyx commented on internal/server/auth/auth_test.go
> +func Test_authenticator_Authenticate(t *testing.T) {
По поводу моков обгововрили делаем как тут https://github.com/Dipress/bgwebmon-go/pull/4/files#diff-860aaddefd34ac6241cd00073c4254b2R22

2018-09-28 06:18 UTC, closed without merging